less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":10,' | sort > chr10.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":11,' | sort > chr11.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":12,' | sort > chr12.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":13,' | sort > chr13.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":14,' | sort > chr14.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":15,' | sort > chr15.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":16,' | sort > chr16.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":17,' | sort > chr17.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":18,' | sort > chr18.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":19,' | sort > chr19.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":20,' | sort > chr20.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":21,' | sort > chr21.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":22,' | sort > chr22.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":23,' | sort > chr23.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":24,' | sort > chr24.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":25,' | sort > chr25.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":1,' | sort > chr1.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":2,' | sort > chr2.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":3,' | sort > chr3.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":4,' | sort > chr4.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":5,' | sort > chr5.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":6,' | sort > chr6.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":7,' | sort > chr7.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":8,' | sort > chr8.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":9,' | sort > chr9.original.json
less -S GRCh38_dbsnp_146.json| grep -v 'ncbi' | grep '"c":10,' | sort > chr10.original.json

